spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpashop?user=root
    username: jpashop
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
# org.hibernate.type: trace #스프링 부트 2.x, hibernate5
